version: "3.7"

services:
    web:
        build: .
        container_name: "demo_app_django"
        volumes:
            - .:/usr/src/app
        command: /start

        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - redis
            - postgres-db

    postgres-db:
        image: postgres:12.0-alpine
        env_file:
            - ./.env
        volumes:
            - pgdata:/var/lib/postgresql/data

    celery:
        build: .
        container_name: "demo_app_celery"
        command: celery -A config worker -l INFO
        volumes:
            - .:/code
        env_file:
            - ./.env
        depends_on:
            - redis
            - web
    celery-beat:
        build: .
        container_name: "demo_app_celery_beat"
        command: celery -A config beat -l INFO
        volumes:
            - .:/code
        env_file:
            - ./.env
        depends_on:
            - redis
            - web
    redis:
        image: redis

volumes:
    pgdata:
