# Generated by Django 4.0.4 on 2022-04-12 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('product_name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('current_price', models.IntegerField(verbose_name='Текущая цена')),
                ('old_price', models.IntegerField(verbose_name='Старая цена')),
                ('brand_name', models.CharField(max_length=150, verbose_name='Название бренда')),
                ('supplier', models.CharField(max_length=150, verbose_name='Поставщик')),
            ],
        ),
        migrations.CreateModel(
            name='CardTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_tracking', models.DateTimeField()),
                ('end_tracking', models.DateTimeField()),
                ('interval', models.TimeField(choices=[('1 hour', 1), ('12 hours', 12), ('24 hours', 24)])),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_card', to='statistic.productcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
