# Generated by Django 3.2.13 on 2022-04-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_tracking', models.DateTimeField()),
                ('end_tracking', models.DateTimeField()),
                ('interval', models.PositiveIntegerField(choices=[(1, '1 hour'), (12, '12 hours'), (24, '24 hours')])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Артикул')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('current_price', models.PositiveIntegerField(verbose_name='Текущая цена')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Старая цена')),
                ('brand_name', models.CharField(max_length=150, verbose_name='Название бренда')),
                ('supplier', models.CharField(max_length=150, verbose_name='Поставщик')),
                ('tracked_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='statistic.productcard', verbose_name='Артикул')),
            ],
        ),
    ]
