# Generated by Django 4.0.4 on 2022-04-12 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtracking',
            name='interval',
            field=models.DateField(choices=[('1:00:00', '1 hour'), ('12:00:00', '12 hours'), (datetime.timedelta(days=1), '24 hours')]),
        ),
    ]
