# Generated by Django 4.0.4 on 2022-04-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_alter_cardtracking_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtracking',
            name='interval',
            field=models.TimeField(),
        ),
    ]
