# Generated by Django 4.0.4 on 2022-04-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_alter_cardtracking_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtracking',
            name='interval',
            field=models.PositiveIntegerField(choices=[(1, '1 hour'), (12, '12 hours'), (24, '24 hours')]),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='current_price',
            field=models.PositiveIntegerField(verbose_name='Текущая цена'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='old_price',
            field=models.PositiveIntegerField(verbose_name='Старая цена'),
        ),
    ]
