# Generated by Django 4.0.4 on 2022-04-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0005_alter_cardtracking_interval_alter_productcard_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtracking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
