# Generated by Django 4.0.4 on 2022-04-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0006_cardtracking_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='supplier',
        ),
        migrations.CreateModel(
            name='ProductCardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('current_price', models.PositiveIntegerField(verbose_name='Текущая цена')),
                ('old_price', models.PositiveIntegerField(verbose_name='Старая цена')),
                ('brand_name', models.CharField(max_length=150, verbose_name='Название бренда')),
                ('supplier', models.CharField(max_length=150, verbose_name='Поставщик')),
                ('tracked_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='statistic.productcard', verbose_name='Артикул')),
            ],
        ),
    ]
