# Generated by Django 4.0.4 on 2022-04-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0010_alter_productcard_user_alter_productcardstate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcardstate',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Старая цена'),
        ),
    ]
