# Generated by Django 4.0.4 on 2022-04-13 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0011_alter_productcardstate_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcardstate',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='statistic.productcard', verbose_name='Артикул'),
        ),
    ]
