# Generated by Django 3.2.13 on 2022-04-21 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0012_alter_productcardstate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtracking',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_card', to='statistic.productcard', unique=True),
        ),
    ]
